# Generated by Django 5.0.4 on 2024-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_control_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='peso',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso (Kg.)'),
        ),
        migrations.AlterField(
            model_name='control',
            name='vacunas',
            field=models.ManyToManyField(blank=True, null=True, to='perfil.vacunas'),
        ),
    ]
