# Generated by Django 5.0.4 on 2024-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_remove_control_ultima_visita_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='fecha_control',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
