# Generated by Django 5.0.4 on 2024-05-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_alter_mascota_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.mascota'),
        ),
    ]
