# Generated by Django 5.0.4 on 2024-05-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_mascota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
    ]
