# Generated by Django 5.0.4 on 2024-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_control_castrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
