# Generated by Django 5.0.4 on 2024-05-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_control_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='otras_intervenciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='alimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='datos_importantes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
