# Generated by Django 5.0.4 on 2024-05-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Veterinarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=250, null=True)),
                ('foto_referencia', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidad.localidad')),
            ],
            options={
                'verbose_name': 'Veterinaria',
                'verbose_name_plural': 'Veterinarias',
            },
        ),
    ]
