# Generated by Django 5.0.4 on 2024-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarias',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='veterinarias',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='veterinarias',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='veterinarias',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ubicación'),
        ),
    ]
