# Generated by Django 5.0.4 on 2024-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_alter_veterinarias_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarias',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='teléfono'),
        ),
    ]
