# Generated by Django 5.0.4 on 2024-05-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_alter_veterinarias_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animales',
            },
        ),
        migrations.CreateModel(
            name='TipCuriosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tip_o_curiosidad', models.CharField(choices=[('tip', 'Tip'), ('curiosidad', 'Curiosidad')], max_length=10, verbose_name='Tip o curiosidad')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='URL')),
                ('dato', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comunidad.tipoanimal')),
            ],
            options={
                'verbose_name': 'Tip o curiosidad',
                'verbose_name_plural': 'Tips o curiosidades',
            },
        ),
    ]
